version: "2.1"
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=wireguard.domain.com #optional
      - SERVERPORT=51820 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - ${WG_CONFIG}:/config
      - /lib/modules:/lib/modules
    ports:
      #- 51820:51820/udp #wireguard server
      - 8989:8989 #sonarr
      - 9091:9091 #transmission
      - 51413:51413
      - 51413:51413/udp
      - 9117:9117 #jackett
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${SON_DATA}:/config
      - ${MEDIA_TV}:/tv
      - ${MEDIA_DOWNLOADS}:/downloads
    restart: unless-stopped
    network_mode: service:wireguard

  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=${TRAN_USER} #optional
      - PASS=${TRAN_PASS} #optional
      #- WHITELIST=iplist #optional
    volumes:
      - ${TRAN_CONFIG}:/config
      - ${MEDIA_DOWNLOADS}:/downloads
      - ${TRAN_WATCH}:/watch
    #ports:
    #  - 9091:9091
    #  - 51413:51413
    #  - 51413:51413/udp
    restart: unless-stopped
    network_mode: service:wireguard

  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
      #- RUN_OPTS=<run options here> #optional
    volumes:
      - ${JAC_CONFIG}:/config
      - ${MEDIA_DOWNLOADS}:/downloads
    #ports:
    #  - 9117:9117
    restart: unless-stopped
    network_mode: service:wireguard

  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${EMBY_CONFIG}:/config
      - ${MEDIA_TV}:/data/tvshows
    ports:
      - 8096:8096
      - 8920:8920 #optional
    devices:
      - /dev/dri:/dev/dri #optional
    restart: unless-stopped
